name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install gperf
    
    - name: Create method files
      run: make gperf
    
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add ./interpreter
    - name: commit changed files
      run: git commit -m "Auto updating .methods files"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
